services:
  nats: 
    image: nats:latest
    container_name: msgb-nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
      - "9222:9222"
    volumes:
      - ./nats.conf:/nats.conf
    command: ["-c" , "/nats.conf"]